port: /dev/neo-s300-1
baud: 500000
scan_cycle_time: 0.080
scan_duration: 0.050
scan_delay: 0.030
frame_id: lidar_1_link
scan_intervals: [[-1.48, 1.48]] #[rad] these intervals are included to the scan +-85°
