NeoLocalPlanner:

  # The x acceleration limit of the robot in meters/sec^2
  acc_lim_x : 0.5

  # The y acceleration limit of the robot in meters/sec^2
  acc_lim_y : 0.5

  # The rotational acceleration limit of the robot in radians/sec^2
  acc_lim_theta : 1

  # The maximum x velocity for the robot in m/s.
  max_vel_x : 0.8

  # The minimum x velocity for the robot in m/s, negative for backwards motion.
  min_vel_x : -0.1

  # The minimum y velocity for the robot in m/s
  min_vel_y : -0.5

  # The maximum y velocity for the robot in m/s
  max_vel_y : 0.5

  # The absolute value of the maximum rotational velocity for the robot in rad/s
  max_rot_vel : 1

  # The absolute value of the minimum rotational velocity for the robot in rad/s
  min_rot_vel : 0.1

  # The absolute value of the maximum translational velocity for the robot in m/s
  max_trans_vel : 0.8

  # The absolute value of the minimum translational velocity for the robot in m/s
  min_trans_vel : 0.1

  # The tolerance in radians for the controller in yaw/rotation when achieving its goal
  yaw_goal_tolerance : 0.02

  # The tolerance in meters for the controller in the x & y distance when achieving a goal
  xy_goal_tolerance : 0.1

  # How far to predict control pose into the future based on latest odometry [s]
  lookahead_time : 0.2

  # How far to look ahead when computing path orientation (or looking for goal) [m]
  lookahead_dist : 0.5

  # Maximum y error for lane keeping, below we adjust velocity, above we stop and rotate [m]
  max_y_error : 0.2

  # Maximum yaw error for lane keeping, below we adjust velocity, above we stop and rotate [rad]
  max_yaw_error : 1

  # Gain when adjusting final x position for goal [1/s]
  pos_x_gain : 1

  # Gain for lane keeping based on y error (differential only) [rad/s^2]
  pos_y_yaw_gain : 1

  # Gain for lane keeping based on yaw error (differential only) [1/s]
  yaw_gain : 2

  # Gain for adjusting yaw when not translating, or in case of holonomic drive  [1/s]
  static_yaw_gain : 3

  # Max velocity based on yawrate (default = min_trans_vel * max_rot_vel) [m*rad/s^2]
  max_curve_vel : 0.15

  # Max distance allowable for backing up (zero = unlimited) [m]
  max_backup_dist : 0.1

  # If robot has differential drive, holonomic otherwise
  differential_drive : true
